### PR TITLE
Scope

### PR DESCRIPTION
**Pull request by rajastakilos**
Added scope to query whether a game has a black or white id open.

### CODE REVIEW

**Review by dtrypt — CHANGES_REQUESTED** [review]
Move the colons back a space and space after the colons instead, like so:
`scope :available, -> { where(black_id: null).or(where(white_id: null)) }`
And Rubocop is tripping out about the extra line before end.

**Comment by sungwon** [comment]
Also, as you noted in Slack, this way of doing it will work for Rails 5, but not Rails 4. So either we will need to upgrade the app to Rails 5 (and we should have the team's consensus for this) or we will have to do it the Rails 4 way (see link in the Slack convo for an example).

**Review by koglesby — CHANGES_REQUESTED** [review]
If I'm not mistaken, I think white_id and black_id should be called white_player and black_player, as that's what they are called in the schema

**Comment by sungwon** [comment]
@koglesby good catch!

**Review by dtrypt — COMMENTED** [review]
We can delete this PR.

**Pull request closed without merging**
