### PR TITLE
Setup STI for piece models

### PR DESCRIPTION
**Pull request by rouxcaesar**
Pull Request for Single Table Inheritance of all chess piece models.
- Added column type through a migration to piece.rb model
- Created models for chess pieces (Rook, Knight, Bishop, Queen, King, Pawn).
- Edited each chess piece model to inherit from piece.rb model

Checked with Sungwon and discussed scope of this task, where by this code should meet the current scope. Please review and give any feedback!

### CODE REVIEW

**Review by sungwon — CHANGES_REQUESTED** [review]
Just 1 more thing needs to be done to set up STI. On the Piece model, you have to set "self.inheritance_column". See the Animal example: https://devblast.com/b/single-table-inheritance-with-rails-4-part-1

**Review by dtrypt — COMMENTED** [review]
My understanding is that you don't actually need the self.inheritance_column line because you used the default STI name: type. In the example, they used "race" as the inheritance column, so they have that extra line.

"The race column is going to be used by Active Record to save the submodel name. By default, AR will search for a column named type but you can use anything as long as you tell AR about it."

Sungwon correct me if I'm wrong.

**Comment by sungwon** [comment]
@trustinruss Yes, I believe you are correct. Thanks for catching that!

**Review by sungwon — APPROVED** [review]

**Review by dtrypt — APPROVED** [review]

**Review by koglesby — APPROVED** [review]
Looks good to me. I don't see any need for the piece_type column which was already in the schema, so maybe we can get rid of that in another PR

**Pull request merged**
