### PR TITLE
Draw pieces

### PR DESCRIPTION
**Pull request by koglesby**
After creating a new game, the board will display each piece in its starting position as text that identifies the piece color and type.

Each square passes through the values of its position in the 2D array to a helper method, which checks to see if there is a piece at the horizontal_position and vertical_position in the database, and renders a string with the piece type and color if one is found.

### CODE REVIEW

**Review by dtrypt — CHANGES_REQUESTED** [review]
Looks good so far. I think the scope of this task included finding the chess piece images online and rendering the images onto the squares (after starting with just text)

**Comment by koglesby** [comment]
The images for each piece are now loaded on the board instead of the text description. 
I still haven't figured out how to keep the squares that have pieces in them from stretching into rectangles.

**Review by dtrypt — APPROVED** [review]
Nice, I didn't think of using a naming convention in the assets/images to target the pieces. Clever!
The tiles get a bit skewed but we can probably fix that later.

**Review by sungwon — APPROVED** [review]
Yep, CSS is... annoying. It looks like the problem is with: [https://github.com/8th-Rank-Pawns/chess-app/blob/87fe62747b70be9f41f3afdae609c6ce3402ff89/app/assets/stylesheets/master.css.scss#L53](https://github.com/8th-Rank-Pawns/chess-app/blob/87fe62747b70be9f41f3afdae609c6ce3402ff89/app/assets/stylesheets/master.css.scss#L53)

It needs to be a different percentage for squares that have pieces in them. 

Please either fix it and get it re-approved or merge this in as is and create a bug in the backlog to fix it later.

**Comment by koglesby** [comment]
sort of a dirty solution, that I'm sure I can refactor, but it works right now

**Review by dtrypt — COMMENTED** [review]
Right now the pieces are non-responsive and the empty empty squares are responsive. I think we should have a fixed board size that's non-responsive.

**Review by sungwon — APPROVED** [review]
Nice, just add a task to the backlog for the responsiveness bug.

**Comment by koglesby** [comment]
The other option is to add the image responsive class to the pieces, so that the pieces and their squares scale with the rest of the board when we adjust the window size, which I think would be good

**Pull request merged**
