### PR TITLE
rubocop should be up to date

### PR DESCRIPTION
**Pull request by rajastakilos**

### CODE REVIEW

**Review by dtrypt — APPROVED** [review]
looks good

**Comment by sungwon** [comment]
Great job fixing all those "offenses"! Just move the configuration that you have in the .rubocop_todo.yml into .rubocop.yml, so that we now have a an empty "todo".

**Review by sungwon — CHANGES_REQUESTED** [review]
Great job fixing all those "offenses"! Just move the configuration that you have in the .rubocop_todo.yml into .rubocop.yml, so that we now have a an empty "todo" (removing some comments that are no longer applicable like "Offense count").

**Review by dtrypt — APPROVED** [review]

**Comment by sungwon** [comment]
This is replaced by: https://github.com/8th-Rank-Pawns/chess-app/pull/10

**Pull request closed without merging**
