### PR TITLE
List available games on homepage

### PR DESCRIPTION
**Pull request by koglesby**
Available games get listed out in chess index view, added scope in game model, made a factory in that has both black_player and white_player assigned for a game (through factory for user), and a test to see if it gets listed as available.

### CODE REVIEW

**Comment by LesleyPark** [comment]
Looks good but one minor nitpick. There's some duplicated code for the "Sign in with Facebook" functionality on the index page. Not a huge deal though since the Facebook authentication has been moved into the sign up/sign in page already so we'd most likely be deleting this from index.html.erb anyway.

**Review by LesleyPark — APPROVED** [review]

**Comment by koglesby** [comment]
Good catch. Right now I just removed the duplication, but it sounds like we'll want to remove the sign-out/sign-in code from the index page entirely

**Review by dtrypt — APPROVED** [review]
Nicely done. I'll move the facebook sign in to the navbar on my next pull request.

**Review by sungwon — APPROVED** [review]
Nicely done, @koglesby, good reviewing, @LesleyPark and thanks for staying on top of all the merge requests, @trustinruss !

**Comment by LesleyPark** [comment]
@trustinruss, Facebook sign in is already listed as an option on the Sign Up/Sign In pages (links to both in the top nav). It looks like it gets pulled in automatically with <%= render "devise/shared/links" %>. Maybe we can add an icon or something to make the Facebook sign in link pop a little more? The file to edit for that should be _links.html.erb in views/devise/shared.

**Pull request merged**
