### PR TITLE
Built CRUD for Game Model

### PR DESCRIPTION
**Pull request by rouxcaesar**
- Created the GamesController and included the New, Show, and Create actions as per the Task card.
- Wrote RSpec tests for the New, Show, and Create actions. The New and Show actions currently fail for ActionView::MissingTemplate (missing view files), which I believe is Lesley's Task card. Please correct me if I'm mistaken and should create generic view files.
- Installed Simple Form gem and changed config/initializers/simple_form.rb with config.input_class to make the form look better.
- Game model was already created by Kevin and was incorporated here.

Please review and let me know of any potential improvements!

### CODE REVIEW

**Review by sungwon — CHANGES_REQUESTED** [review]
Looks good. Just add blank files for the views, so those tests pass and while you're at it could you  please remove the extra folder "chess-app-8th-rank-pawns" that got added to an older pull request somehow (it's the last task in the backlog).

Also, no need to create a separate trello card for the pull request. Just move the card into the pull request column.

**Review by koglesby — COMMENTED** [review]
Agreed with Sungwon - I think just adding in the basic views would be good, but other than that, I don't see any  problems

**Review by dtrypt — CHANGES_REQUESTED** [review]
Just two things -
1. Still need to update this pull request to have views so tests pass.
2. We need to assign players to games when they're created, so the game_params method in the games_controller should permit :white_player and :black_player (please correct me if you disagree).

& remember to delete the "pending" line in games_helper_spec.rb that creates empty tests.

To update your pull request-
Commit and push changes to the crud branch in your local repo ($git add, $git -m, $git push origin crud) and the PR should automatically update :)

**Comment by sungwon** [comment]
Looking good. 

@trustinruss ' suggestion to assign players is a good one, but let's not worry about it right now. 

Last thing to be done I think is just to 'Exclude' the schema file from the 'Prefer single-quoted strings when you don't need string interpolation or special symbols.' Rubocop offense setting and fix the whitespace offense.

**Review by sungwon — APPROVED** [review]

**Review by dtrypt — APPROVED** [review]

**Review by koglesby — APPROVED** [review]
Looks good!

**Pull request merged**
