### PR TITLE
Added valid_move? for rooks, bishops, queens, and knights. Also added commonly…

### PR DESCRIPTION
**Pull request by LesleyPark**
…used checks (diagonal?, horizontal_or_vertical?, did_not_move?) in piece.rb

### CODE REVIEW

**Review by sungwon — CHANGES_REQUESTED** [review]
Looks really good. I like how you factored out common functionality in the Piece model.  

Let's just write some tests for these (or put a task in the backlog to do it later).

**Review by sungwon — APPROVED** [review]

**Review by koglesby — APPROVED** [review]
Looks good! Way to tackle valid_move? for almost all of the pieces

**Review by dtrypt — COMMENTED** [review]
Nice job on all the logic and organization, looks awesome!
-Should we call the did_not_move method should be called on the knight and the rook?

**Comment by LesleyPark** [comment]
@trustinruss, don't think so! valid_move? for the rook will only return true if there are changes in either horizontal_position or vertical_position (sans obstructions); by definition you can't not have movement and return a true. Similarly, the knight will only return true if both horizontal_position and vertical_position have changed by increments of 1 or 2. The reason I needed to call the did_not_move? method for the bishop (and by extension the queen) was because I defined diagonal movement as having the same change in both the horizontal (x) and vertical (y) directions. In that case, a delta of (0, 0) would also return as true without the did_not_move? check.

**Review by dtrypt — APPROVED** [review]
You're right! My B

**Pull request merged**
