### PR TITLE
Added chessboard in games#show + top nav

### PR DESCRIPTION
**Pull request by LesleyPark**
Added the chessboard in games#show and added a not-so-pretty but functional top nav bar since I figure we'll probably need that at some point.

### CODE REVIEW

**Review by dtrypt — COMMENTED** [review]
Hey Lesley, I had to hack a new game into the console to see your chessboard but it looks good. Nice job on the css. My suggestion is to add a "new game" button on the homepage that creates a game and sends users to that game.
Also... I was curious so I changed the html tags in the view into ruby code:
```
<div class="board">
  <% board = Array.new(8) %>
  <% board.map! {Array(1..8)}%>
  <% board.each do |row| %>
    <div class="row">
      <% row.each do || %>
        <div></div>
        <% end %>
    </div>
  <% end %>
</div>
```

It works the same but more compact. It will also make it easier to assign labels to tiles.

**Comment by LesleyPark** [comment]
Great suggestions! Editing show.html.erb now; will add a new game button to the home page in a little bit.

**Review by sungwon — APPROVED** [review]
Looks nice. I like the backgrounds, too.

**Review by koglesby — APPROVED** [review]
Nice, the games/show page looks a lot DRY-er with the new changes

**Pull request merged**
